go test command:
	cd ..; go test -run 'ObjdumpLOONG64TestDecodeGUNSyntaxdata' -v -timeout 10h -long 2>&1 | tee -a log
	cd ..; go test -run 'TestDecodeGNUSyntax'
	cd ..; go test -run 'ObjdumpLOONG64Manual' -v -timeout 10h -long 2>&1 | tee -a log
	cd ..; go test -run '.*'
